In [2]:
import metaheuristic_designer as mhd
from metaheuristic_designer import ObjectiveVectorFunc
import numpy as np

In [3]:
class TresureHunt(ObjectiveVectorFunc):
    def __init__(self, n_moves, n_tresures, grid_size=(10,10),name: str = "Tresure Hunt"):
        self.n_moves = n_moves
        self.n_tresures = n_tresures
        self.grid_size = np.array(grid_size)

        # We define a grid with n_treasures
        grid_flat = np.zeros(grid_size).flatten()
        grid_flat[:n_tresures] = 1
        np.random.shuffle(grid_flat)
        self.grid = grid_flat.reshape(grid_size)

        # We specify the size of the vector (n_moves), wether to maximize or minimize (mode),
        # lower limit (low_lim), upper limit (up_lim) and name of the function (name).
        super().__init__(n_moves, mode="max", low_lim=0, up_lim=4, name=name)
    
    def objective(self, move_vector):
        collected = 0

        move_set = np.array([
            [ 0, 1],
            [ 1, 0],
            [ 0,-1],
            [-1, 0]
        ])

        pos = np.array([0,0])
        grid_copy = self.grid.copy()
        for move in move_vector:
            new_pos = pos + move_set[move]

            if new_pos[0] >= 0 and new_pos[0] < self.grid_size[0] and new_pos[1] >= 0 and new_pos[1] < self.grid_size[1]:
                pos = new_pos

                if grid_copy[*pos] == 1:
                    collected += 1
                    grid_copy[pos] = 0
            
            print(pos)
        
        return collected

objfunc = TresureHunt(10, 10)
print(objfunc.grid)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
